<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>MyComputerManager</RootNamespace>
    <AssemblyName>MyComputerManager</AssemblyName>
    <ApplicationIcon>Resources\openbox.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyVersion>1.4.0.0</AssemblyVersion>
    <FileVersion>1.4.0.0</FileVersion>
    <Version>1.4.0</Version>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\openbox.ico" />
    <Resource Include="Resources\addimage.svg" />
    <Resource Include="Resources\copy.svg" />
    <Resource Include="Resources\folder.svg" />
    <Resource Include="Resources\openbox.svg" />
    <Resource Include="Resources\reg.svg" />
    <Resource Include="Resources\title.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.3.0" />
  </ItemGroup>

</Project>